version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: strdb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    build:
      context: ./Hermes
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    restart: on-failure
  frontend:
    build:
      context: ./TalkToMe
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"